/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { banUser } from '../fn/admin-controller/ban-user';
import { BanUser$Params } from '../fn/admin-controller/ban-user';
import { getAllUsers } from '../fn/admin-controller/get-all-users';
import { GetAllUsers$Params } from '../fn/admin-controller/get-all-users';
import { PageResponseUserResponse } from '../models/page-response-user-response';
import { testSicurezza1 } from '../fn/admin-controller/test-sicurezza-1';
import { TestSicurezza1$Params } from '../fn/admin-controller/test-sicurezza-1';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `banUser()` */
  static readonly BanUserPath = '/admin/ban/{user-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `banUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  banUser$Response(params: BanUser$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return banUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `banUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  banUser(params: BanUser$Params, context?: HttpContext): Observable<void> {
    return this.banUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllUsers()` */
  static readonly GetAllUsersPath = '/admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsers$Response(params?: GetAllUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserResponse>> {
    return getAllUsers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsers(params?: GetAllUsers$Params, context?: HttpContext): Observable<PageResponseUserResponse> {
    return this.getAllUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseUserResponse>): PageResponseUserResponse => r.body)
    );
  }

  /** Path part for operation `testSicurezza1()` */
  static readonly TestSicurezza1Path = '/admin/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `testSicurezza1()` instead.
   *
   * This method doesn't expect any request body.
   */
  testSicurezza1$Response(params?: TestSicurezza1$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return testSicurezza1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `testSicurezza1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  testSicurezza1(params?: TestSicurezza1$Params, context?: HttpContext): Observable<{
}> {
    return this.testSicurezza1$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
