/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { banBakery } from '../fn/admin-controller/ban-bakery';
import { BanBakery$Params } from '../fn/admin-controller/ban-bakery';
import { banUser } from '../fn/admin-controller/ban-user';
import { BanUser$Params } from '../fn/admin-controller/ban-user';
import { enableBakery } from '../fn/admin-controller/enable-bakery';
import { EnableBakery$Params } from '../fn/admin-controller/enable-bakery';
import { getAllBakery } from '../fn/admin-controller/get-all-bakery';
import { GetAllBakery$Params } from '../fn/admin-controller/get-all-bakery';
import { getAllRequest } from '../fn/admin-controller/get-all-request';
import { GetAllRequest$Params } from '../fn/admin-controller/get-all-request';
import { getAllUsers } from '../fn/admin-controller/get-all-users';
import { GetAllUsers$Params } from '../fn/admin-controller/get-all-users';
import { PageResponseBakeryRegisterRequest } from '../models/page-response-bakery-register-request';
import { PageResponseBakeryResponse } from '../models/page-response-bakery-response';
import { PageResponseUserResponse } from '../models/page-response-user-response';
import { rejectRequest } from '../fn/admin-controller/reject-request';
import { RejectRequest$Params } from '../fn/admin-controller/reject-request';
import { searchByName } from '../fn/admin-controller/search-by-name';
import { SearchByName$Params } from '../fn/admin-controller/search-by-name';
import { testSicurezza1 } from '../fn/admin-controller/test-sicurezza-1';
import { TestSicurezza1$Params } from '../fn/admin-controller/test-sicurezza-1';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `enableBakery()` */
  static readonly EnableBakeryPath = '/admin/enableBakery';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `enableBakery()` instead.
   *
   * This method doesn't expect any request body.
   */
  enableBakery$Response(params: EnableBakery$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return enableBakery(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `enableBakery$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  enableBakery(params: EnableBakery$Params, context?: HttpContext): Observable<{
}> {
    return this.enableBakery$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `banUser()` */
  static readonly BanUserPath = '/admin/ban';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `banUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  banUser$Response(params: BanUser$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return banUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `banUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  banUser(params: BanUser$Params, context?: HttpContext): Observable<void> {
    return this.banUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `banBakery()` */
  static readonly BanBakeryPath = '/admin/banBakery';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `banBakery()` instead.
   *
   * This method doesn't expect any request body.
   */
  banBakery$Response(params: BanBakery$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return banBakery(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `banBakery$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  banBakery(params: BanBakery$Params, context?: HttpContext): Observable<void> {
    return this.banBakery$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllUsers()` */
  static readonly GetAllUsersPath = '/admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsers$Response(params?: GetAllUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserResponse>> {
    return getAllUsers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsers(params?: GetAllUsers$Params, context?: HttpContext): Observable<PageResponseUserResponse> {
    return this.getAllUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseUserResponse>): PageResponseUserResponse => r.body)
    );
  }

  /** Path part for operation `testSicurezza1()` */
  static readonly TestSicurezza1Path = '/admin/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `testSicurezza1()` instead.
   *
   * This method doesn't expect any request body.
   */
  testSicurezza1$Response(params?: TestSicurezza1$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return testSicurezza1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `testSicurezza1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  testSicurezza1(params?: TestSicurezza1$Params, context?: HttpContext): Observable<{
}> {
    return this.testSicurezza1$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `searchByName()` */
  static readonly SearchByNamePath = '/admin/searchByName';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchByName()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchByName$Response(params: SearchByName$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBakeryRegisterRequest>> {
    return searchByName(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchByName$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchByName(params: SearchByName$Params, context?: HttpContext): Observable<PageResponseBakeryRegisterRequest> {
    return this.searchByName$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBakeryRegisterRequest>): PageResponseBakeryRegisterRequest => r.body)
    );
  }

  /** Path part for operation `getAllRequest()` */
  static readonly GetAllRequestPath = '/admin/getAllRequest';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllRequest()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRequest$Response(params?: GetAllRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBakeryRegisterRequest>> {
    return getAllRequest(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllRequest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRequest(params?: GetAllRequest$Params, context?: HttpContext): Observable<PageResponseBakeryRegisterRequest> {
    return this.getAllRequest$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBakeryRegisterRequest>): PageResponseBakeryRegisterRequest => r.body)
    );
  }

  /** Path part for operation `getAllBakery()` */
  static readonly GetAllBakeryPath = '/admin/getAllBakery';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllBakery()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBakery$Response(params?: GetAllBakery$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBakeryResponse>> {
    return getAllBakery(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllBakery$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBakery(params?: GetAllBakery$Params, context?: HttpContext): Observable<PageResponseBakeryResponse> {
    return this.getAllBakery$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBakeryResponse>): PageResponseBakeryResponse => r.body)
    );
  }

  /** Path part for operation `rejectRequest()` */
  static readonly RejectRequestPath = '/admin/rejectRequest';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rejectRequest()` instead.
   *
   * This method doesn't expect any request body.
   */
  rejectRequest$Response(params: RejectRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return rejectRequest(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rejectRequest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rejectRequest(params: RejectRequest$Params, context?: HttpContext): Observable<{
}> {
    return this.rejectRequest$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
