/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { updateWeek } from '../fn/bakery-controller/update-week';
import { UpdateWeek$Params } from '../fn/bakery-controller/update-week';

@Injectable({ providedIn: 'root' })
export class BakeryControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateWeek()` */
  static readonly UpdateWeekPath = '/bakery/updateWeek';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateWeek()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateWeek$Response(params: UpdateWeek$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return updateWeek(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateWeek$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateWeek(params: UpdateWeek$Params, context?: HttpContext): Observable<{
}> {
    return this.updateWeek$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
