/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { bakeryDetail } from '../fn/front-end-controller/bakery-detail';
import { BakeryDetail$Params } from '../fn/front-end-controller/bakery-detail';
import { BakeryfrontEndResponse } from '../models/bakeryfront-end-response';
import { getRandomData } from '../fn/front-end-controller/get-random-data';
import { GetRandomData$Params } from '../fn/front-end-controller/get-random-data';
import { RandomDataBakeryResponse } from '../models/random-data-bakery-response';

@Injectable({ providedIn: 'root' })
export class FrontEndControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getRandomData()` */
  static readonly GetRandomDataPath = '/frontEnd/getRandomData';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRandomData()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRandomData$Response(params: GetRandomData$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RandomDataBakeryResponse>>> {
    return getRandomData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRandomData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRandomData(params: GetRandomData$Params, context?: HttpContext): Observable<Array<RandomDataBakeryResponse>> {
    return this.getRandomData$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RandomDataBakeryResponse>>): Array<RandomDataBakeryResponse> => r.body)
    );
  }

  /** Path part for operation `bakeryDetail()` */
  static readonly BakeryDetailPath = '/frontEnd/bakery/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bakeryDetail()` instead.
   *
   * This method doesn't expect any request body.
   */
  bakeryDetail$Response(params: BakeryDetail$Params, context?: HttpContext): Observable<StrictHttpResponse<BakeryfrontEndResponse>> {
    return bakeryDetail(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bakeryDetail$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bakeryDetail(params: BakeryDetail$Params, context?: HttpContext): Observable<BakeryfrontEndResponse> {
    return this.bakeryDetail$Response(params, context).pipe(
      map((r: StrictHttpResponse<BakeryfrontEndResponse>): BakeryfrontEndResponse => r.body)
    );
  }

}
