/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { findAllTest } from '../fn/test/find-all-test';
import { FindAllTest$Params } from '../fn/test/find-all-test';
import { findAllTestByOwner } from '../fn/test/find-all-test-by-owner';
import { FindAllTestByOwner$Params } from '../fn/test/find-all-test-by-owner';
import { findById } from '../fn/test/find-by-id';
import { FindById$Params } from '../fn/test/find-by-id';
import { PageResponseTestResponse } from '../models/page-response-test-response';
import { saveTest } from '../fn/test/save-test';
import { SaveTest$Params } from '../fn/test/save-test';
import { TestResponse } from '../models/test-response';
import { updateField } from '../fn/test/update-field';
import { UpdateField$Params } from '../fn/test/update-field';
import { uploadCoverPictures } from '../fn/test/upload-cover-pictures';
import { UploadCoverPictures$Params } from '../fn/test/upload-cover-pictures';

@Injectable({ providedIn: 'root' })
export class TestService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAllTest()` */
  static readonly FindAllTestPath = '/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllTest()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllTest$Response(params?: FindAllTest$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTestResponse>> {
    return findAllTest(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllTest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllTest(params?: FindAllTest$Params, context?: HttpContext): Observable<PageResponseTestResponse> {
    return this.findAllTest$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseTestResponse>): PageResponseTestResponse => r.body)
    );
  }

  /** Path part for operation `saveTest()` */
  static readonly SaveTestPath = '/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveTest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveTest$Response(params: SaveTest$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveTest(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveTest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveTest(params: SaveTest$Params, context?: HttpContext): Observable<number> {
    return this.saveTest$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `uploadCoverPictures()` */
  static readonly UploadCoverPicturesPath = '/test/cover/{test-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadCoverPictures()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadCoverPictures$Response(params: UploadCoverPictures$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return uploadCoverPictures(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadCoverPictures$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadCoverPictures(params: UploadCoverPictures$Params, context?: HttpContext): Observable<{
}> {
    return this.uploadCoverPictures$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `updateField()` */
  static readonly UpdateFieldPath = '/test/test-field/{test-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateField()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateField$Response(params: UpdateField$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateField(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateField$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateField(params: UpdateField$Params, context?: HttpContext): Observable<number> {
    return this.updateField$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findById()` */
  static readonly FindByIdPath = '/test/{test-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findById$Response(params: FindById$Params, context?: HttpContext): Observable<StrictHttpResponse<TestResponse>> {
    return findById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findById(params: FindById$Params, context?: HttpContext): Observable<TestResponse> {
    return this.findById$Response(params, context).pipe(
      map((r: StrictHttpResponse<TestResponse>): TestResponse => r.body)
    );
  }

  /** Path part for operation `findAllTestByOwner()` */
  static readonly FindAllTestByOwnerPath = '/test/owner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllTestByOwner()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllTestByOwner$Response(params?: FindAllTestByOwner$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTestResponse>> {
    return findAllTestByOwner(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllTestByOwner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllTestByOwner(params?: FindAllTestByOwner$Params, context?: HttpContext): Observable<PageResponseTestResponse> {
    return this.findAllTestByOwner$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseTestResponse>): PageResponseTestResponse => r.body)
    );
  }

}
