/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addAddress } from '../fn/user-controller/add-address';
import { AddAddress$Params } from '../fn/user-controller/add-address';
import { addToCart } from '../fn/user-controller/add-to-cart';
import { AddToCart$Params } from '../fn/user-controller/add-to-cart';
import { addToFav } from '../fn/user-controller/add-to-fav';
import { AddToFav$Params } from '../fn/user-controller/add-to-fav';
import { BakeryFav } from '../models/bakery-fav';
import { Cart } from '../models/cart';
import { checkIfOwner } from '../fn/user-controller/check-if-owner';
import { CheckIfOwner$Params } from '../fn/user-controller/check-if-owner';
import { checkOwnerOfBakery } from '../fn/user-controller/check-owner-of-bakery';
import { CheckOwnerOfBakery$Params } from '../fn/user-controller/check-owner-of-bakery';
import { getAddress } from '../fn/user-controller/get-address';
import { GetAddress$Params } from '../fn/user-controller/get-address';
import { getAllForCart } from '../fn/user-controller/get-all-for-cart';
import { GetAllForCart$Params } from '../fn/user-controller/get-all-for-cart';
import { getAllItems } from '../fn/user-controller/get-all-items';
import { GetAllItems$Params } from '../fn/user-controller/get-all-items';
import { getAllOrders } from '../fn/user-controller/get-all-orders';
import { GetAllOrders$Params } from '../fn/user-controller/get-all-orders';
import { getCart } from '../fn/user-controller/get-cart';
import { GetCart$Params } from '../fn/user-controller/get-cart';
import { getCurrentUser } from '../fn/user-controller/get-current-user';
import { GetCurrentUser$Params } from '../fn/user-controller/get-current-user';
import { getFav } from '../fn/user-controller/get-fav';
import { GetFav$Params } from '../fn/user-controller/get-fav';
import { getUser } from '../fn/user-controller/get-user';
import { GetUser$Params } from '../fn/user-controller/get-user';
import { getUserInfo } from '../fn/user-controller/get-user-info';
import { GetUserInfo$Params } from '../fn/user-controller/get-user-info';
import { isAdmin } from '../fn/user-controller/is-admin';
import { IsAdmin$Params } from '../fn/user-controller/is-admin';
import { isToFav } from '../fn/user-controller/is-to-fav';
import { IsToFav$Params } from '../fn/user-controller/is-to-fav';
import { ItemsCart } from '../models/items-cart';
import { ListCatForCart } from '../models/list-cat-for-cart';
import { modQuantityItem } from '../fn/user-controller/mod-quantity-item';
import { ModQuantityItem$Params } from '../fn/user-controller/mod-quantity-item';
import { OrderFrontEnd } from '../models/order-front-end';
import { PageResponseUserResponse } from '../models/page-response-user-response';
import { removeToCart } from '../fn/user-controller/remove-to-cart';
import { RemoveToCart$Params } from '../fn/user-controller/remove-to-cart';
import { remToFav } from '../fn/user-controller/rem-to-fav';
import { RemToFav$Params } from '../fn/user-controller/rem-to-fav';
import { searchUserByName } from '../fn/user-controller/search-user-by-name';
import { SearchUserByName$Params } from '../fn/user-controller/search-user-by-name';
import { sendOrder } from '../fn/user-controller/send-order';
import { SendOrder$Params } from '../fn/user-controller/send-order';
import { sendRequest } from '../fn/user-controller/send-request';
import { SendRequest$Params } from '../fn/user-controller/send-request';
import { Status } from '../models/status';
import { testSicurezza } from '../fn/user-controller/test-sicurezza';
import { TestSicurezza$Params } from '../fn/user-controller/test-sicurezza';
import { TokenVerifyResponse } from '../models/token-verify-response';
import { uploadProfilePicture } from '../fn/user-controller/upload-profile-picture';
import { UploadProfilePicture$Params } from '../fn/user-controller/upload-profile-picture';
import { UserFrontEndInfoResponse } from '../models/user-front-end-info-response';
import { UserFrontEndResponse } from '../models/user-front-end-response';
import { verificaEmail } from '../fn/user-controller/verifica-email';
import { VerificaEmail$Params } from '../fn/user-controller/verifica-email';
import { verifyToken } from '../fn/user-controller/verify-token';
import { VerifyToken$Params } from '../fn/user-controller/verify-token';

@Injectable({ providedIn: 'root' })
export class UserControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `verifyToken()` */
  static readonly VerifyTokenPath = '/user/verificaToken';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verifyToken()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verifyToken$Response(params: VerifyToken$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenVerifyResponse>> {
    return verifyToken(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verifyToken$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verifyToken(params: VerifyToken$Params, context?: HttpContext): Observable<TokenVerifyResponse> {
    return this.verifyToken$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenVerifyResponse>): TokenVerifyResponse => r.body)
    );
  }

  /** Path part for operation `verificaEmail()` */
  static readonly VerificaEmailPath = '/user/verificaEmail';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificaEmail()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verificaEmail$Response(params: VerificaEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return verificaEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificaEmail$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verificaEmail(params: VerificaEmail$Params, context?: HttpContext): Observable<{
}> {
    return this.verificaEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `uploadProfilePicture()` */
  static readonly UploadProfilePicturePath = '/user/upload-profile-picture';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadProfilePicture()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadProfilePicture$Response(params: UploadProfilePicture$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return uploadProfilePicture(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadProfilePicture$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadProfilePicture(params: UploadProfilePicture$Params, context?: HttpContext): Observable<{
}> {
    return this.uploadProfilePicture$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `sendRequest()` */
  static readonly SendRequestPath = '/user/sendRequest';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendRequest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendRequest$Response(params: SendRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return sendRequest(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendRequest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendRequest(params: SendRequest$Params, context?: HttpContext): Observable<{
}> {
    return this.sendRequest$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `sendOrder()` */
  static readonly SendOrderPath = '/user/sendOrder';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendOrder()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendOrder$Response(params?: SendOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return sendOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendOrder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendOrder(params?: SendOrder$Params, context?: HttpContext): Observable<{
}> {
    return this.sendOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `removeToCart()` */
  static readonly RemoveToCartPath = '/user/removeToCart';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeToCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeToCart$Response(params: RemoveToCart$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return removeToCart(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeToCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeToCart(params: RemoveToCart$Params, context?: HttpContext): Observable<{
}> {
    return this.removeToCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `addToFav()` */
  static readonly AddToFavPath = '/user/addToFav';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addToFav()` instead.
   *
   * This method doesn't expect any request body.
   */
  addToFav$Response(params: AddToFav$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return addToFav(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addToFav$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  addToFav(params: AddToFav$Params, context?: HttpContext): Observable<{
}> {
    return this.addToFav$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `addToCart()` */
  static readonly AddToCartPath = '/user/addToCart';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addToCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  addToCart$Response(params: AddToCart$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return addToCart(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addToCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  addToCart(params: AddToCart$Params, context?: HttpContext): Observable<{
}> {
    return this.addToCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `addAddress()` */
  static readonly AddAddressPath = '/user/addAddress';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addAddress()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addAddress$Response(params: AddAddress$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return addAddress(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addAddress$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addAddress(params: AddAddress$Params, context?: HttpContext): Observable<{
}> {
    return this.addAddress$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `modQuantityItem()` */
  static readonly ModQuantityItemPath = '/user/modQuantityItem';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `modQuantityItem()` instead.
   *
   * This method doesn't expect any request body.
   */
  modQuantityItem$Response(params: ModQuantityItem$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return modQuantityItem(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `modQuantityItem$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  modQuantityItem(params: ModQuantityItem$Params, context?: HttpContext): Observable<{
}> {
    return this.modQuantityItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getUser()` */
  static readonly GetUserPath = '/user/{user-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUser$Response(params: GetUser$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUser(params: GetUser$Params, context?: HttpContext): Observable<{
}> {
    return this.getUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `testSicurezza()` */
  static readonly TestSicurezzaPath = '/user/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `testSicurezza()` instead.
   *
   * This method doesn't expect any request body.
   */
  testSicurezza$Response(params?: TestSicurezza$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return testSicurezza(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `testSicurezza$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  testSicurezza(params?: TestSicurezza$Params, context?: HttpContext): Observable<{
}> {
    return this.testSicurezza$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `searchUserByName()` */
  static readonly SearchUserByNamePath = '/user/searchUserByName';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchUserByName()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchUserByName$Response(params: SearchUserByName$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserResponse>> {
    return searchUserByName(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchUserByName$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchUserByName(params: SearchUserByName$Params, context?: HttpContext): Observable<PageResponseUserResponse> {
    return this.searchUserByName$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseUserResponse>): PageResponseUserResponse => r.body)
    );
  }

  /** Path part for operation `getCurrentUser()` */
  static readonly GetCurrentUserPath = '/user/me';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUser$Response(params?: GetCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserFrontEndResponse>> {
    return getCurrentUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUser(params?: GetCurrentUser$Params, context?: HttpContext): Observable<UserFrontEndResponse> {
    return this.getCurrentUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserFrontEndResponse>): UserFrontEndResponse => r.body)
    );
  }

  /** Path part for operation `isAdmin()` */
  static readonly IsAdminPath = '/user/isAdmin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `isAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  isAdmin$Response(params?: IsAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return isAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `isAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  isAdmin(params?: IsAdmin$Params, context?: HttpContext): Observable<boolean> {
    return this.isAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `getUserInfo()` */
  static readonly GetUserInfoPath = '/user/info';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserInfo$Response(params?: GetUserInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<UserFrontEndInfoResponse>> {
    return getUserInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserInfo(params?: GetUserInfo$Params, context?: HttpContext): Observable<UserFrontEndInfoResponse> {
    return this.getUserInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserFrontEndInfoResponse>): UserFrontEndInfoResponse => r.body)
    );
  }

  /** Path part for operation `getFav()` */
  static readonly GetFavPath = '/user/getFav';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFav()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFav$Response(params?: GetFav$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BakeryFav>>> {
    return getFav(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFav$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFav(params?: GetFav$Params, context?: HttpContext): Observable<Array<BakeryFav>> {
    return this.getFav$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<BakeryFav>>): Array<BakeryFav> => r.body)
    );
  }

  /** Path part for operation `getCart()` */
  static readonly GetCartPath = '/user/getCart';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCart$Response(params?: GetCart$Params, context?: HttpContext): Observable<StrictHttpResponse<Cart>> {
    return getCart(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCart(params?: GetCart$Params, context?: HttpContext): Observable<Cart> {
    return this.getCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<Cart>): Cart => r.body)
    );
  }

  /** Path part for operation `getAllOrders()` */
  static readonly GetAllOrdersPath = '/user/getAllOrders';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllOrders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOrders$Response(params?: GetAllOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderFrontEnd>>> {
    return getAllOrders(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllOrders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOrders(params?: GetAllOrders$Params, context?: HttpContext): Observable<Array<OrderFrontEnd>> {
    return this.getAllOrders$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OrderFrontEnd>>): Array<OrderFrontEnd> => r.body)
    );
  }

  /** Path part for operation `getAllItems()` */
  static readonly GetAllItemsPath = '/user/getAllItems';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllItems()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllItems$Response(params?: GetAllItems$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ItemsCart>>> {
    return getAllItems(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllItems$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllItems(params?: GetAllItems$Params, context?: HttpContext): Observable<Array<ItemsCart>> {
    return this.getAllItems$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ItemsCart>>): Array<ItemsCart> => r.body)
    );
  }

  /** Path part for operation `getAllForCart()` */
  static readonly GetAllForCartPath = '/user/getAllItemForCart';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllForCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllForCart$Response(params: GetAllForCart$Params, context?: HttpContext): Observable<StrictHttpResponse<ListCatForCart>> {
    return getAllForCart(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllForCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllForCart(params: GetAllForCart$Params, context?: HttpContext): Observable<ListCatForCart> {
    return this.getAllForCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<ListCatForCart>): ListCatForCart => r.body)
    );
  }

  /** Path part for operation `getAddress()` */
  static readonly GetAddressPath = '/user/getAddress';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAddress()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAddress$Response(params?: GetAddress$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getAddress(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAddress$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAddress(params?: GetAddress$Params, context?: HttpContext): Observable<{
}> {
    return this.getAddress$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `checkOwnerOfBakery()` */
  static readonly CheckOwnerOfBakeryPath = '/user/checkOwnerOfBakery';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkOwnerOfBakery()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkOwnerOfBakery$Response(params?: CheckOwnerOfBakery$Params, context?: HttpContext): Observable<StrictHttpResponse<Status>> {
    return checkOwnerOfBakery(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkOwnerOfBakery$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkOwnerOfBakery(params?: CheckOwnerOfBakery$Params, context?: HttpContext): Observable<Status> {
    return this.checkOwnerOfBakery$Response(params, context).pipe(
      map((r: StrictHttpResponse<Status>): Status => r.body)
    );
  }

  /** Path part for operation `isToFav()` */
  static readonly IsToFavPath = '/user/checkIsToFav';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `isToFav()` instead.
   *
   * This method doesn't expect any request body.
   */
  isToFav$Response(params: IsToFav$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return isToFav(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `isToFav$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  isToFav(params: IsToFav$Params, context?: HttpContext): Observable<boolean> {
    return this.isToFav$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `checkIfOwner()` */
  static readonly CheckIfOwnerPath = '/user/checkIfOwner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkIfOwner()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkIfOwner$Response(params?: CheckIfOwner$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return checkIfOwner(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkIfOwner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkIfOwner(params?: CheckIfOwner$Params, context?: HttpContext): Observable<boolean> {
    return this.checkIfOwner$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `remToFav()` */
  static readonly RemToFavPath = '/user/remToFav';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `remToFav()` instead.
   *
   * This method doesn't expect any request body.
   */
  remToFav$Response(params: RemToFav$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return remToFav(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `remToFav$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  remToFav(params: RemToFav$Params, context?: HttpContext): Observable<{
}> {
    return this.remToFav$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
