/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { User } from '../models/user';
export interface BakeryRegisterRequest {
  address?: Address;
  description?: string;
  email_azz?: string;
  facebook?: string;
  id?: number;
  instagram?: string;
  name?: string;
  phone_azz?: string;
  twitter?: string;
  user?: User;
}
