/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { ContactInfo } from '../models/contact-info';
export interface BakeryfrontEndResponse {
  Logo?: string;
  address?: Address;
  desc?: string;
  id?: number;
  info?: ContactInfo;
  logo?: string;
  name?: string;
  openInHours?: string;
  owner?: number;
}
