/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { Category } from '../models/category';
import { ContactInfo } from '../models/contact-info';
import { Order } from '../models/order';
import { User } from '../models/user';
import { Week } from '../models/week';
export interface Bakery {
  abilitato?: boolean;
  address?: Address;
  categories?: Array<Category>;
  contactInfo?: ContactInfo;
  description?: string;
  id?: number;
  images?: Array<string>;
  name?: string;
  openStatus?: boolean;
  orders?: Array<Order>;
  owner?: User;
  registrationDate?: string;
  url_backImg?: string;
  url_picture?: string;
  week?: Week;
}
