/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { Category } from '../models/category';
import { User } from '../models/user';
export interface BakeryResponse {
  address?: Address;
  categorys?: Array<Category>;
  enable?: boolean;
  id?: number;
  name?: string;
  owner?: User;
  url_picture?: string;
}
