/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemsCart } from '../models/items-cart';
export interface Cart {
  id?: number;
  idBac?: number;
  items?: Array<ItemsCart>;
  total?: number;
}
