/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemForCart } from '../models/item-for-cart';
export interface CategoryForCart {
  id?: number;
  items?: Array<ItemForCart>;
  name?: string;
  owner?: number;
}
