/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Item } from '../models/item';
export interface Category {
  id?: number;
  items?: Array<Item>;
  name?: string;
  owner?: number;
}
