/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactInfo {
  email?: string;
  facebook?: string;
  id?: number;
  instagram?: string;
  phone?: string;
  twitter?: string;
}
