/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ItemForCart {
  description?: string;
  id?: number;
  img?: string;
  name?: string;
  price?: number;
  quantity?: number;
}
