/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Item } from '../models/item';
export interface ItemsCart {
  details?: Item;
  id?: number;
  quantity?: number;
  subTotal?: number;
}
