/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JwtToken {
  expired?: boolean;
  id?: number;
  revoked?: boolean;
  token?: string;
  userId?: number;
}
