/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryForCart } from '../models/category-for-cart';
export interface ListCatForCart {
  categorys?: Array<CategoryForCart>;
  id_azz?: number;
  img_azz?: string;
  name_azz?: string;
}
