/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Category } from '../models/category';
export interface ListCategoryFrontEnd {
  categorys?: Array<Category>;
  id_azz?: number;
  img_azz?: string;
  name_azz?: string;
}
