/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { Bakery } from '../models/bakery';
import { ItemsCart } from '../models/items-cart';
import { User } from '../models/user';
export interface Order {
  accepted?: boolean;
  address?: Address;
  bakery?: Bakery;
  id?: number;
  items?: Array<ItemsCart>;
  status?: string;
  totalPrice?: number;
  user?: User;
}
