/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { ItemsCart } from '../models/items-cart';
export interface OrderFrontEnd {
  accepted?: boolean;
  address?: Address;
  id?: number;
  idBac?: number;
  items?: Array<ItemsCart>;
  nameAzz?: string;
  status?: string;
  totalPrice?: number;
}
