/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BakeryRegisterRequest } from '../models/bakery-register-request';
export interface PageResponseBakeryRegisterRequest {
  content?: Array<BakeryRegisterRequest>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
