/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RandomDataBakeryCarosello {
  desc?: string;
  id?: number;
  img?: string;
  name?: string;
}
