/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TestResponse {
  description?: string;
  id?: number;
  name?: string;
  owner?: string;
  test_url?: Array<string>;
}
