/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { BakeryFav } from '../models/bakery-fav';
import { Cart } from '../models/cart';
import { GrantedAuthority } from '../models/granted-authority';
import { JwtToken } from '../models/jwt-token';
import { Order } from '../models/order';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  address?: Address;
  authorities?: Array<GrantedAuthority>;
  cart?: Cart;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enable?: boolean;
  enabled?: boolean;
  fav?: Array<BakeryFav>;
  id?: number;
  lastModifiedDate?: string;
  name?: string;
  orders?: Array<Order>;
  password?: string;
  roles?: 'CUSTOMER' | 'BAKERY_OWNER' | 'ADMIN';
  tokens?: Array<JwtToken>;
  url_BackImg?: string;
  url_picture?: string;
  userName?: string;
  username?: string;
}
