/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface UserFrontEndInfoResponse {
  address?: Address;
  email?: string;
  id?: number;
  url_back?: string;
  url_picture?: string;
  username?: string;
}
