/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  accountLocked?: boolean;
  email?: string;
  enable?: boolean;
  id?: number;
  url_picture?: string;
  username?: string;
}
