/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { GrantedAuthority } from '../models/granted-authority';
import { JwtToken } from '../models/jwt-token';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  address?: Address;
  authorities?: Array<GrantedAuthority>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enable?: boolean;
  enabled?: boolean;
  id?: number;
  lastModifiedDate?: string;
  name?: string;
  password?: string;
  roles?: 'CUSTOMER' | 'BAKERY_OWNER' | 'ADMIN';
  tokens?: Array<JwtToken>;
  url_BackImg?: string;
  url_picture?: string;
  userName?: string;
  username?: string;
}
