/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseBakeryRegisterRequest } from '../../models/page-response-bakery-register-request';

export interface SearchByName$Params {
  name: string;
  page?: number;
  size?: number;
}

export function searchByName(http: HttpClient, rootUrl: string, params: SearchByName$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBakeryRegisterRequest>> {
  const rb = new RequestBuilder(rootUrl, searchByName.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseBakeryRegisterRequest>;
    })
  );
}

searchByName.PATH = '/admin/searchByName';
