/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Status } from '../../models/status';

export interface CheckOwnerOfBakery$Params {
}

export function checkOwnerOfBakery(http: HttpClient, rootUrl: string, params?: CheckOwnerOfBakery$Params, context?: HttpContext): Observable<StrictHttpResponse<Status>> {
  const rb = new RequestBuilder(rootUrl, checkOwnerOfBakery.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Status>;
    })
  );
}

checkOwnerOfBakery.PATH = '/user/checkOwnerOfBakery';
