/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListCatForCart } from '../../models/list-cat-for-cart';

export interface GetAllForCart$Params {
  idBac: number;
}

export function getAllForCart(http: HttpClient, rootUrl: string, params: GetAllForCart$Params, context?: HttpContext): Observable<StrictHttpResponse<ListCatForCart>> {
  const rb = new RequestBuilder(rootUrl, getAllForCart.PATH, 'get');
  if (params) {
    rb.query('idBac', params.idBac, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListCatForCart>;
    })
  );
}

getAllForCart.PATH = '/user/getAllItemForCart';
