/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BakeryfrontEndResponse } from '../../models/bakeryfront-end-response';

export interface BakeryDetail$Params {
  id: number;
}

export function bakeryDetail(http: HttpClient, rootUrl: string, params: BakeryDetail$Params, context?: HttpContext): Observable<StrictHttpResponse<BakeryfrontEndResponse>> {
  const rb = new RequestBuilder(rootUrl, bakeryDetail.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BakeryfrontEndResponse>;
    })
  );
}

bakeryDetail.PATH = '/frontEnd/bakery/{id}';
