/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BakeryNavBarResponse } from '../../models/bakery-nav-bar-response';

export interface GetBAkeryById$Params {
  idBac: number;
}

export function getBAkeryById(http: HttpClient, rootUrl: string, params: GetBAkeryById$Params, context?: HttpContext): Observable<StrictHttpResponse<BakeryNavBarResponse>> {
  const rb = new RequestBuilder(rootUrl, getBAkeryById.PATH, 'get');
  if (params) {
    rb.query('idBac', params.idBac, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BakeryNavBarResponse>;
    })
  );
}

getBAkeryById.PATH = '/frontEnd/getBAkeryById';
