/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlanAddBkery } from '../../models/plan-add-bkery';

export interface GetPlaneAdd$Params {
  id: number;
}

export function getPlaneAdd(http: HttpClient, rootUrl: string, params: GetPlaneAdd$Params, context?: HttpContext): Observable<StrictHttpResponse<PlanAddBkery>> {
  const rb = new RequestBuilder(rootUrl, getPlaneAdd.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlanAddBkery>;
    })
  );
}

getPlaneAdd.PATH = '/frontEnd/getPlaneAddress';
