/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RandomDataBakeryResponse } from '../../models/random-data-bakery-response';

export interface GetRandomData$Params {
  id: number;
}

export function getRandomData(http: HttpClient, rootUrl: string, params: GetRandomData$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RandomDataBakeryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getRandomData.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RandomDataBakeryResponse>>;
    })
  );
}

getRandomData.PATH = '/frontEnd/getRandomData';
