/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Week } from '../../models/week';

export interface GetWeek$Params {
  idBakery: number;
}

export function getWeek(http: HttpClient, rootUrl: string, params: GetWeek$Params, context?: HttpContext): Observable<StrictHttpResponse<Week>> {
  const rb = new RequestBuilder(rootUrl, getWeek.PATH, 'get');
  if (params) {
    rb.query('idBakery', params.idBakery, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Week>;
    })
  );
}

getWeek.PATH = '/frontEnd/getWeek';
