/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RandomDataBakeryCarosello } from '../../models/random-data-bakery-carosello';

export interface GetRandomForCarosello$Params {
}

export function getRandomForCarosello(http: HttpClient, rootUrl: string, params?: GetRandomForCarosello$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RandomDataBakeryCarosello>>> {
  const rb = new RequestBuilder(rootUrl, getRandomForCarosello.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RandomDataBakeryCarosello>>;
    })
  );
}

getRandomForCarosello.PATH = '/frontEnd/getRandomForCarosello';
