/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListCategoryFrontEnd } from '../../models/list-category-front-end';

export interface GetAllCategory$Params {
  owner: number;
}

export function getAllCategory(http: HttpClient, rootUrl: string, params: GetAllCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<ListCategoryFrontEnd>> {
  const rb = new RequestBuilder(rootUrl, getAllCategory.PATH, 'get');
  if (params) {
    rb.query('owner', params.owner, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListCategoryFrontEnd>;
    })
  );
}

getAllCategory.PATH = '/frontEnd/getAllCategory';
