/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderFrontEnd } from '../../models/order-front-end';

export interface GetAllOrdersBakery$Params {
}

export function getAllOrdersBakery(http: HttpClient, rootUrl: string, params?: GetAllOrdersBakery$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderFrontEnd>>> {
  const rb = new RequestBuilder(rootUrl, getAllOrdersBakery.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderFrontEnd>>;
    })
  );
}

getAllOrdersBakery.PATH = '/bakery/getAllOrdersBakery';
