/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemRequest } from '../../models/item-request';

export interface UpdateItem$Params {
  idItem: number;
  idBac: number;
      body: ItemRequest
}

export function updateItem(http: HttpClient, rootUrl: string, params: UpdateItem$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, updateItem.PATH, 'post');
  if (params) {
    rb.query('idItem', params.idItem, {});
    rb.query('idBac', params.idBac, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

updateItem.PATH = '/bakery/modItem';
